- hosts: ansible-terraform
  tasks:
  - name: instalar dependências python
    apt:
      pkg:
      - python3
      - virtualenv
      update_cache: yes
    become: yes
  - name: instalar dependências django/rest
    pip:
      virtualenv: /home/ubuntu/tcc-ana/venv
      name: 
        - django
        - djangorestframework
  - name: iniciar projeto 
    shell: ". /home/ubuntu/tcc-ana/venv/bin/activate; django-admin startproject setup /home/ubuntu/tcc-ana/"
  - name: configurar hosts do settings
    lineinfile:
      path: /home/ubuntu/tcc-ana/setup/settings.py
      regexp: "ALLOWED_HOSTS"
      line: "ALLOWED_HOSTS = ['*']"
      backrefs: yes
